### ISSUE TITLE
Error when EAC log's track numbers do not start from 1

### ISSUE THREAD

**Issue by metaisfacil** [doujincafe/hbcl#9]
Using the latest HBCL pip installed from this repo. The current logic for parsing an EAC log simply extracts the direct track number from the log's TOC table and plugs it as a key in the `LogFile.toc` dict. HBCL currently assumes the TOC table (and therefore the dict) will always start from track 1, and if it doesn't a KeyError is thrown in the `is_there_a_htoa()` method.

Example affected log file: [Various Artists - Zennihon Satsugai Sai Kyou Getemono Ouzakettei Rigusen.log](https://github.com/doujincafe/hbcl/files/10699239/Various.Artists.-.Zennihon.Satsugai.Sai.Kyou.Getemono.Ouzakettei.Rigusen.log)
Example script for reproduction:
```
from heybrochecklog import score_log
from pathlib import Path
import os


log_file = os.path.join(os.getcwd(), "Various Artists - Zennihon Satsugai Sai Kyou Getemono Ouzakettei Rigusen.log")
log_report = score_log(Path(log_file))
print(log_report)

```

Output:
```
Traceback (most recent call last):
  File "...\test.py", line 7, in <module>
    log_report = score_log(Path(log_file))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\score\__init__.py", line 16, in score_log
    log = score_wrapper(log, markup)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\score\__init__.py", line 58, in score_wrapper
    log = logchecker.check(log)
          ^^^^^^^^^^^^^^^^^^^^^
  File "...\Python311\Lib\site-packages\heybrochecklog\score\eac.py", line 29, in check
    self.is_there_a_htoa(log)
  File "...\Python311\Lib\site-packages\heybrochecklog\score\eac.py", line 92, in is_there_a_htoa
    if log.toc[1][0] < 450 or not log.range:
       ~~~~~~~^^^
KeyError: 1
```

Conjecture follows. It would seem track numbers on CD's are assigned and not assumed. I don't see any hard restrictions on what track number the disc starts with, or even if they're sequential. The disc the log above derives from is the 2nd in a 2-disc compilation, and the 1st has tracks from 1-9 - so my best guess is the release was originally authored to fit entirely on 1 CD, but they ran out of space (or time) and divided the image lazily resulting in an unusual TOC.

**Comment by fumiichan** [comment]
Thanks for reporting! Patch will be up around this week.
I have notifications muted and didn't seen the issue immediately. Apologies for that.
